---
title: "Weekly Update"
author: "Cappy Pugliese"
date: "2/10 - 2/21"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
linestretch: 1.25
header-includes:
  \usepackage{fontspec}
  \setmainfont{Courier}
---

### Last week (2/10 - 2-14)
- went to grad craft night for the first time, it was very nice
- had my first one-on-one lab meeting of the semester with Andrius
  - lab goals:
    - work on picking research committee members
    - work on getting the lat-long wns data (possibly email and ask)
    - keep on reading
- taught a lot during tutoring hours
  - went overtime a little bit, might need to start being a bit more upfront about how long the tutoring sessions are
- EEB 5300
  - learned about different databases and a bit more about utilizing NCBI
  - worked with navigating around NCBI and looking at genomes
  - learned how to submit a job through SLURM

### For this week
- still struggling a bit to juggle schoolwork and teaching
- I think I need to designate a time to check my email (to limit the amount of time I'm checking it)

### This week (2/17 - 2/21)
#### 2/17
- evolunch: talked about bird hybridization and speciation
- did homework for EEB 5300
- sent email to lab students
- went to craft night again

#### 2/18
- one-on-one lab meeting
  - nf core website
    - has premade pipelines that should work
    - aimed at long reads
  - talked about beginning to write SLURM script
- went into my directory on xanadu for the first time in a while
  - I understand the different file types a lot better now thanks to Jill's class, and I have a better understanding of what I'm doing now
  - did some reorganizing
  - downloaded .gtf and .gff for the pd reference genome to my pd reference folder
- proctored exam for bio1108

#### 2/18-2/21
- spent a lot of time working on the lab work for EEB 5300
  - worked a lot more with sending in jobs using slurm
  - looked at read quality for both long and short reads
  - learned how to filter for contaminants
  - worked with jellyfish and genomescope
  - wrote a script to assemble a genome using flye
- also spent a head-bashingly amount of time fighting github
  - (had some merge errors and I was working on the terminal with github for the first time)
  


