---
title: "11-5-25_weekly-update"
author: "Cappy Pugliese"
date: "11/3 - 11/26"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
linestretch: 1.25
header-includes:
  \usepackage{fontspec}
  \setmainfont{Courier}
---

### This week 11/3-11/7

#### Monday (11/3)

-   ran test iqtree script, worked perfectly fine
-   was able to use seff to figure out how many cores and how much mem I should ask for
-   reran pipe_to_slurm with these new constraints
-   briefly tried to reorganize some of the output, but it was too much to do it all by hand so I stopped
    -   tried to run a couple of the iqtree scripts at the same time
    -   once I figured out how to run them, put them running but they all quit very quickly

#### Wednesday (11/5)

-   realized I didn't have a specified log folder so the scripts were quitting before they could run
-   trying to make changes so I can run them with parallel instead of running them all at the same time
-   I was able to run them with parallel, but they still all ran at the same time??? Not sure why. Kind of defeats the whole purpose of doing that.
-   6/10 of the runs failed with some weird error. Was not able to find solution for the error online. Other people had the same question but neither had been answered.

```{bash}
ERROR: modelfactory.cpp:1131: virtual bool ModelFactory::initFromNestedModel(std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > >): Assertion `itr != checkpoint->end()' failed.
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: NW_020167520.1_1_wnd10000.log
ERROR: ***    Alignment files (if possible)
```

#### Thursday (11/6)

-   tried to briefly troubleshoot iqtree, with no luck

-   tried to get some more lat-long data points, didn't get super far because I had to jump down a lot of rabbit holes

#### Friday (11/7)

-   took Andrius's advice and started annotating some of the sources I had found with zotero

------------------------------------------------------------------------

### Week 11/10 - 11/14

#### Monday (11/10)

-   annotated some more sources

#### Thurs (11/13)

-   tried to rerun iqtree (briefly) but ran into issue - need to fix

-   added new pcangsd graph that groups the data a bit better

-   finished up my short assignment 2

------------------------------------------------------------------------

### Week 11/17-11/26

I have been forgetting to write down the things I've been doing, whoops

#### Monday (11/17)

-   looks like I did a lot

-   I trouble-shooted iqtree and finally got it to work

    -   I switched the version of iqtree to version 2.2.2 and ran into no issues

    -   It looked like it was an issue with the newest version of iqtree itself

-   unsure what I did the rest of the week

#### Monday & Weds (11/24 & 11/26)

-   worked on getting the lat/long metadata

-   finished getting all of the lat/long metadata (may not be the most precise, but I tried my best)