---
title: "12-02-25 weekly update"
author: "Cappy Pugliese"
date: "11/3 - 11/7"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
linestretch: 1.25
header-includes:
  \usepackage{fontspec}
  \setmainfont{Courier}
---

## This week 12/01 - 12/05

### Monday (12/01)

-   started to redo pcangsd without non-pd samples

    -   started rerunning the vcf making process

    -   turns out I didn't need to do that lol

### Tuesday (12/02)

-   new vcf without non-pd samples had finished running

    -   doing some bcftools stats analysis

    -   going a little bit more in depth than last time because I'm trying to figure out what the results mean myself

    -   found a [script](https://mubashir3164.github.io/tutorials/vcf_analysis_tutorial.html) to help with analyzing the vcf, courtesy of [Mubashir Abbas](https://github.com/Mubashir3164) on github

        -   running the script does take a little bit, and I did not realize it also needed vcftools in addition to bcftools at first

### Thursday (12/04)

-   edited stats script and played around with it a bit, also put it running

-   put a filtering script running for the new vcf

-   put a plink script running for the new vcf

## Following week 12/07-12/12

### Sunday (12/07)

-   looked back at stats output

-   plink had run into an error, had to fix

    -   something was wrong with the ld prunning

    -   just took that option out entirely

-   reran plink without any issues

-   put pcangsd running for pd only samples

-   made new pcangsd graphs (had to use a different color scheme because there were too many sub pops)

-   started the process for making pcansd graphs for only north american pd samples

    -   used bcftools view -S this time around instead of redoing everything

    -   used the ploidy-1 vcf (although the vcfs look pretty much the same???? file size and stats-wise)

    -   filtered vcf using the same settings as all the others

### Monday (12/08)

-   ran pcangsd for the north american pd samples

-   made the dataframes for the pcangsd graphs

-   made the pcangsd graphs, and tried to make them a bit better

### Tuesday (12/09)

-   worked on editing the pcangsd graphs for popgen project

    -   spent a while trying to make a better color palette to see all the differences better

### Wednesday (12/10)

-   finished up popgen project

    -   ended up making one more set of pcangsd graphs

    -   added to results section and wrote discussion and broader analysis sections

-   Met Max over zoom and talked to him about the lab and grad school

-   submitted popgen final project