---
title: "Weekly Update"
author: "Cappy Pugliese"
date: "10/07 - 10/11"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
linestretch: 1.25
header-includes:
  \usepackage{fontspec}
  \setmainfont{Courier}
---

### This week
#### 10/08
- finished and presented BEETS presentation

#### 10/09
- talked w/ Andrius about bashrc files, creating aliases (shortcuts), working on the cluster, TA/teaching stuff for next semester
  - goal this week is to follow along with the WNS shared file on the cluster
- got more familiar with the terminal and made a command cheat sheet
- logged into the storrs cluster
- created some file directories
- attempted to download data from NCBI
  - tried to use a python package shortcut
  - had issues installing the package
  - may try to trouble shoot another day/figure out another way to download the data
  
#### 10/10
- tried trouble shooting installing package and failed
  - giving up on using this package
- learned that the storrs HPC does not have sratoolkit installed

#### 10/11
- was finally able to download fastq file using sratoolkit on the farmington cluster
- tried to analyze using fastqc but run was killed
  - generated a fastqc zip file but not a viewable html file
  - looks like I may have run out of memory