---
title: "Weekly Update"
author: "Cappy Pugliese"
date: "11/17 - 11/22"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
linestretch: 1.25
header-includes:
  \usepackage{fontspec}
  \setmainfont{Courier}
---

### This Week
#### 11/17
- took my cat on a hike :)
- worked on 3rd grade outreach presentation
- updated last week's weekly update

#### 11/18
- dentist appointment
- worked more on my preproposal

#### 11/19
- made symlinks to get to the lab directory and the PD genome reference folder
- was going to try to use the files in the reference folder run the bwa mem command, but I quickly ran into permissions issues
- created a reference dict with picard
- indexed with bwa
- bwa mem command still "could not locate index files"
  - banged my head against a wall for an hour while I tried to troubleshoot again
    - had trouble naming the location of the index files
    - then started running into a "command not found" error
      - I had accidentally included "bash-4.2$" text in my code at some point because of a copy error
    - ended up putting all the files in one folder out of frustration
    - finally realized I had a copy error
    - finally got things working
    
#### 11/20
- cleaned up and reorganized things
- finished re-editing the bam file
- still ended up running into the "failed to open file" error
  - realized it was because I did not properly located the files
- tried to start the gatk pipeline as well, but the cluster does not have the gatk software already downloaded as a module
  - was able to download gatk from github and unzip the file
  - I'm unsure how to get gatk to work from here