---
title: "01-26-26 weekly update"
author: "Cappy Pugliese"
date: "1/26 - 1/30"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
linestretch: 1.25
header-includes:
  \usepackage{fontspec}
  \setmainfont{Courier}
---

## This week 1/26 - 1/30

todos:
- need to edit the scripts to get rid of the slurm headers in order for them to work with the slurm array
  - edit the pipe2slurm script to turn them into .sh (no slurm headers) instead of .sbatch

- focus on algatr

### Monday (1/26)
- looked through algatr stuff again
  - discovered that the `do_everything_for_me()` code I had tried to use last time failed because the vector memory limit of my laptop had been reached, so if I want to test everything out, I'd probably need to do it on the cluster
  - decided to go through the TESS vignette portion of the tutorial
    - recommended ld pruning my vcf
    - tried to ld prune using the algatr software but was having difficulty
    - decided to try to ld prune using plink instead and output a new vcf
      - transferred ld prunned vcf file onto my laptop from cluster

### Tuesday (1/27)
- realized I needed to do some other stuff first in the tutorial before starting TESS
  - did the genetic data processing portion
    - learned some stuff, but did not need to do most of it because I already have an ld prunned vcf file
  - started the environmental data processing portion
    - I had already started doing some of this without knowing there was a tutorial for it
    - made sure my coordinates were projected properly
    - did some collinearity tests on the bioclimatic data
    - started to make a raster pca but ran into issues
      - next steps are to troubleshoot

### Wednesday (1/28)
- made a lot of progress with the environmental data processing portion
  - kept running into error after error, but eventually got the code to work for me

## Week 2/2 - 2/6
### Monday (2/2)
- finished the genetics distance section
- made src.R for running algatr
- worked on tess
  - finished all of it
  - ending map was very wonky, did not separate out by color for some reason
  - entire map was all the same color
    - tried to troubleshoot, but there is very little information online about algatr besides the paper and the github itself
    - no one else has seemed to run into this issue
    - am unsure if it has something to do with my coords or my raster, because everything up until the tess ggplot mapping worked fine
  - the normal tess plot worked fine using base tess without algatr
  - unsure what the issue is

### Tuesday (2/3)
- worked on homework for phylogenetics
  - made my own python script to do the calculations

### Wednesday (2/4)
- troubleshot algatr tess not working with Andrius
  - we were able to figure out what looked funky and fix it
  - I was able to generate the plot!
- started working on wingen portion
  - spent a while trying to figure out which projection to use
    - eventually found Goode Homolosine projection
    - works for calculation, but the map looks really funky, I might be able to find a slightly better one?
  - successfully generated a plot map of pi
    - working on making the map look more readable with krigging and masking