---
title: "02-23-26 weekly update"
author: "Cappy Pugliese"
date: "2/23 - 2/27"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
linestretch: 1.25
header-includes:
  \usepackage{fontspec}
  \setmainfont{Courier}
---

## This week 2/23 - 2/27
### focus on (from last week):
- [] look into running FEEMS
- [x] PCA plot
  - might have to follow the pcangsd tutorial
  - [x] without washington
  - [x] with all original (Pd) samples
- [x] wingen
- [] eventually might want to run RDA

### Monday (2/23)
- figured out how to make PCA plot based on PCAngasd covariance matrix
- made a bunch of PCA plots
    - messed around with what the points were colored by
    - it looks like instrument and single vs paired might have some effect because they kind of form some groups
    - by year, lat, and long were somewhat more mixed
    - also tried to look at by collection type (i.e. bat species host, cave wall, etc.) but I had to go down a lot of rabbit holes and not all samples had this information so I gave up for the time being

### Wednesday (2/25)
- made PCA plots for all original Pd samples (similar to what I did on Monday)
- finished wingen
- downloaded feems onto the cluster

### Thurs (2/26)
- sent email to schedule MS defense
  - heard back from Jill
  - it looks like Dan is currently away and not able to respond

### Sat (2/28)
- applied for summer graduation

## Week 3/2 - 3/6
### focus on:
- [] estimating Fst using pixy
- [] add to thesis draft
- [] finish reading lab meeting paper
- [] look through article (slack)
    - focus on sections 6 and 7

### to keep in mind:
- figure out PCA percentages
    - eigen/ec matrix
    - number of PC# over total
- use pixy to calculate population statistics
    - look at pi over time
    - or pi since starting point
- graph: Fst and distance between pops (will show isolation by distance)
    - should have a positive correlation
    - shows that over time that they have become different
- euclidian distance doesn't capture everything (doesn't scale for certain things)
    - proportion of shared alleles --> try (DPS)
    - bray-curtis --> try
- keep working on FEEMS
- eventually send follow up email (scheduling MS defense)

### Monday (3/2)
today todos
- [x] look into running pixy
  - made a script
  - banging my head against a metaphorical wall
  - troubleshooting mania
  - pixy is unable to find invariants, causing it to stop early
    - something goes wrong when ignoring invariants and also stops early
    - not recommended to ignore invariants anyway, I just wanted to see if it would even run, and it didn't
  - ideas after taking a break:
    - try with an unfiltered vcf --> not sure if that is the best, but maybe I've filtered out some of the allsites by accident???
    - try again with a different pixy version. Maybe there is something wrong with this beta version?
    - message andrius if all else fails
- finally got pixy running (I think? I'll need to go back and check)
  - had to use unfiltered vcf
  - had to change the years to text --> pixy did not like the numbers
  - had to change Fst_type to hudson instead of the default
- [x] finish reading lab meeting paper
- [x] look through article (slack)
    - focus on sections 6 and 7

### Wednesday (3/4)
- [x] check on pixy run
- made input to run pixy using the pcangsd pops
  - also put that running
- used awk to clean up the pixy run and get rid of all the NAs and non-useful(?) information
- downloaded files to laptop

### before next lab meeting:
- [x] send in comments for lab meeting paper
  - include line numbers
  - major and minor comments

### Friday (3/6)
- redid pixy run with window size equal to 10000
- worked with data in R
  - used the results from dxy to get rid of most of the NAs that were in the fst data
  - ignoring the rest of the NAs (small portion)
  - manipulated the data many times to try and get it into a violin plot
  - made some (like 3) plots

## Week 3/9 - 3/13
### Monday (3/9)
- [x] focus on feems
  - downloaded miniconda and installed feems on my laptop instead of using the cluster
  - got positron working with my conda environment
  - able to run feems interactively with positron
- started following the tutorial
  - my current plink files were made using the ld tag
  - not a lot of snps
  - might want to go back and redo it without the ld tag
    - nope. literally has the same number of snps
  - was able to generate a plot with the coordinates and the grid
  
- next steps = cross validation tutorial and then the fit feems portion of this tutorial
