---
title: "Weekly Update"
author: "Cappy Pugliese"
date: "5/05 - 5/09"
output: 
  pdf_document:
    latex_engine: xelatex
fontsize: 12pt
linestretch: 1.25
header-includes:
  \usepackage{fontspec}
  \setmainfont{Courier}
---

### Finals Week
#### Monday 5/5
- spent basically the entire day finalizing my final group project's gitlab

#### Tuesday 5/6
- looked back again at the haplotypecaller output
- sorted out all of the samples that ran out of memory and did not finish creating an index file alongside the g.vcf file
- made a new script to re-run just these samples with more memory
- put the new script running and hopefully everything works out 
  - otherwise there might be something else going on or I still didn't give it enough memory
- also did some file tidying up in my own directory

  **future todos:**
    - check to make sure script ran properly and all samples generated an indexed file (.tbi - I'm assuming this is an index file, although I'm not actually sure)
    - trouble shoot if any of the samples didn't run properly
    - merge everything back into one folder if things do run properly
    - can delete the test Pd_03 run from my own directory if run2 works out
    - make the script for the next GVCF process
    